### ISSUE TITLE
"." in dict key is not good for DB

### ISSUE THREAD

**Issue by KipCrossing** [KipCrossing/Aus-Bills#11]
Rename `'Act No.'` to `'Act No'` - without the `.`

**Comment by connorhsm** [comment]
Pretty sure this has been resolved:
` from ausbills.federal_parliment import all_bills, Bill`
` bill = all_bills[0]`
` print(bill)`
*{'chamber': 'House', 'short_title': 'Aboriginal Land Rights (Northern Territory) Amendment (Jabiru) 2020', 'intro_house': datetime.date(2020, 5, 13), 'passed_house': None, 'intro_senate': None, 'passed_senate': None, 'assent_date': None, '**act_no**': '', 'url': 'http://www.aph.gov.au/Parliamentary_Business/Bills_Legislation/Bills_Search_Results/Result?bId=r6536', 'id': 'r6536'}*
 `abill = Bill(bill)`
` print(abill)`
*Aboriginal Land Rights (Northern Territory) Amendment (Jabiru) 2020*
 `print(abill.data)`
*{'chamber': 'House', 'short_title': 'Aboriginal Land Rights (Northern Territory) Amendment (Jabiru) 2020', 'intro_house': '2020-05-13', 'passed_house': '', 'intro_senate': '', 'passed_senate': '', 'assent_date': '', '**act_no**': '',*
