### ISSUE TITLE
Check warning: Bad data 'href'

### ISSUE THREAD

**Issue by KipCrossing** [KipCrossing/Aus-Bills#14]
```
Bad data 'href'  -  Coronavirus Economic Response Package (Payments and Benefits) 2020
```

**Comment by KipCrossing** [comment]
When initiating the Bill object with that bill, that message comes up and I'm not sure why.

**Comment by connorhsm** [comment]
Currently, this is bill 49 in all_bills.
I haven't been able to reproduce this:
``` python
from ausbills.federal_parliment import all_bills, Bill
print(all_bills[49])
bill = all_bills[49]
print(Bill(bill))
print(Bill(bill).summary)
print(Bill(bill).data)
print(Bill(bill).sponsor)
print(Bill(bill).bill_text_links)
print(Bill(bill).explanatory_memoranda_links)
```

Each case printed the expected result.

**Comment by connorhsm** [comment]
@KipCrossing Have you seen this recently? May be time to close this unless it still exists.

**Comment by KipCrossing** [comment]
Ok, if it's not happening in your tests. Should be good to close
