### ISSUE TITLE
Portfolio value is all one string unformatted.

### ISSUE THREAD

**Issue by oscarmanderj** [KipCrossing/Aus-Bills#17]
Portfolio value is all one string unformatted.

eg: 'Communications,CyberSafetyandtheArts'

Can this be fixed to "Communications, Cyber Safety and the Arts"

**Comment by KipCrossing** [comment]
I assumed it was a design decision made by @connorhsm . Sure can though it's an easy fix

**Comment by connorhsm** [comment]
That'd be my lack of QA + late night.

@KipCrossing has resolved as of v0.2.2 or [here](https://github.com/KipCrossing/Aus-Bills/commit/dedc573d8ebaf50e6707db317d86e6dda25fe83c)
